class Example extends Phaser.Scene
{
    constructor ()
    {
        super();
    }

    preload ()
    {
        // Assets live in the /assets folder served at the site root (and copied
        // into the Cordova www/ root for the APK build). setBaseURL is kept
        // root-relative - with no directory climbing - so the same path resolves
        // whether the example runs from GitHub Pages or a file:// WebView.
        this.load.setBaseURL('assets');

        // An 8-frame animated flames sheet (128x160 per frame) plus a matching
        // normal-map sheet, generated by SpriteX. Passing an array of two URLs to
        // load.spritesheet registers the second image as the texture's normal-map
        // data source, so every frame carries its own surface normals and can be
        // lit per-pixel by the Light2D pipeline. Loading as a spritesheet (rather
        // than an atlas) avoids a JSON fetch, which keeps it working under the
        // file:// protocol inside the Cordova WebView.
        //   [0] bg-flames.png            colour (diffuse)
        //   [1] bg-flames-normalmap.png  surface normals (RGB = XYZ)
        this.load.spritesheet(
            'flames',
            [ 'bg-flames.png', 'bg-flames-normalmap.png' ],
            { frameWidth: 128, frameHeight: 160 }
        );
    }

    create ()
    {
        // Loop through the 8 sheet frames to animate the fire.
        this.anims.create({
            key: 'burn',
            frames: this.anims.generateFrameNumbers('flames', { start: 0, end: 7 }),
            frameRate: 12,
            repeat: -1
        });

        // Enable lighting and drop the ambient level so the moving lights read
        // clearly against the dark background.
        this.lights.enable();
        this.lights.setAmbientColor(0x1a1a1a);

        // Build the wall of flames sized to the current screen, and rebuild it
        // (plus re-fit the caption) whenever the game is resized so it always
        // spans 100% of the display.
        this.buildWall();
        this.scale.on('resize', this.onResize, this);

        // A warm key light that follows the pointer - drag it across the flames
        // to watch the normal map catch the fire ridge by ridge.
        this.mouseLight = this.lights.addLight(this.scale.width / 2, this.scale.height / 2, 360, 0xffb060, 3);

        // Two coloured lights sweeping the scene for constant motion.
        this.orbitA = this.lights.addLight(0, 0, 280, 0x3366ff, 2.2);
        this.orbitB = this.lights.addLight(0, 0, 280, 0xff2288, 2.2);

        this.input.on('pointermove', (pointer) =>
        {
            this.mouseLight.x = pointer.x;
            this.mouseLight.y = pointer.y;
        });

        // A single inline instruction line. It follows the camera (fixed on
        // screen) and sits above the flames.
        this.instructions = this.add.text(16, 16, 'Move to light the flames  •  tap to change colour', {
            fontFamily: 'Arial, sans-serif',
            fontSize: '20px',
            color: '#ffd9aa',
            stroke: '#000000',
            strokeThickness: 4
        }).setScrollFactor(0).setDepth(1000);

        // Keep the single line on-screen: shrink it to fit narrow (portrait) widths.
        this.fitInstructions();

        // Click / tap to cycle the key light through a small palette. The first
        // touch also hides the instructions.
        const colors = [ 0xffb060, 0xffffff, 0x00ffcc, 0xff2222, 0x66ff33 ];
        let current = 0;

        this.input.on('pointerdown', () =>
        {
            if (this.instructions)
            {
                this.instructions.destroy();
                this.instructions = null;
            }

            current = (current + 1) % colors.length;
            this.mouseLight.setColor(colors[current]);
        });
    }

    // Match the canvas to its container every frame. Scale.RESIZE only reacts to
    // window resize events, but the viewer's "100%" / live-mode toggle resizes the
    // parent element via a CSS class with no window event - so without this the
    // canvas stays stuck at its boot size and gets letterboxed. Polling the parent
    // size catches container changes however they happen (toggle, rotation, etc.).
    fitToParent ()
    {
        const canvas = this.game.canvas;
        const parent = canvas && canvas.parentElement;

        if (!parent)
        {
            return;
        }

        const w = Math.floor(parent.clientWidth);
        const h = Math.floor(parent.clientHeight);

        if (w > 0 && h > 0 && (Math.abs(this.scale.width - w) > 1 || Math.abs(this.scale.height - h) > 1))
        {
            this.scale.resize(w, h);
        }
    }

    onResize ()
    {
        this.buildWall();
        this.fitInstructions();
    }

    fitInstructions ()
    {
        if (!this.instructions)
        {
            return;
        }

        this.instructions.setScale(1);

        const maxTextWidth = this.scale.width - 32;

        if (this.instructions.width > maxTextWidth)
        {
            this.instructions.setScale(maxTextWidth / this.instructions.width);
        }
    }

    buildWall ()
    {
        const w = this.scale.width;
        const h = this.scale.height;

        // Clear any previous wall (on resize) before rebuilding.
        if (this.flames)
        {
            this.flames.forEach(flame => flame.destroy());
        }

        this.flames = [];

        // Scale each 128x160 frame so the flames stand roughly half the screen
        // tall, clamped so they stay sensible on very short or very tall displays.
        const frameWidth = 128;
        const frameHeight = 160;
        const scale = Phaser.Math.Clamp((h * 0.45) / frameHeight, 1.4, 4);
        const step = frameWidth * scale * 0.82;

        for (let x = -step * 0.5; x < w + step; x += step)
        {
            const flame = this.add.sprite(x, h + 10, 'flames')
                .setOrigin(0.5, 1)
                .setScale(scale)
                .setLighting(true)
                .play('burn');

            // Desync each column so the wall shimmers rather than pulsing as one.
            flame.anims.setProgress(Math.abs(Math.sin(x)));

            this.flames.push(flame);
        }
    }

    update (time)
    {
        // Keep filling the container (catches the live-mode / "100%" toggle).
        this.fitToParent();

        const cx = this.scale.width / 2;
        const h = this.scale.height;

        // Sweep the two coloured lights on opposite paths above the flames,
        // scaled to the current screen size.
        this.orbitA.x = cx + Math.cos(time / 900) * (this.scale.width * 0.42);
        this.orbitA.y = h * 0.45 + Math.sin(time / 900) * (h * 0.25);

        this.orbitB.x = cx + Math.cos(time / 1300 + Math.PI) * (this.scale.width * 0.4);
        this.orbitB.y = h * 0.5 + Math.sin(time / 1300 + Math.PI) * (h * 0.25);
    }
}

const config = {
    type: Phaser.WEBGL,
    backgroundColor: '#000000',
    scene: Example,
    pixelArt: true,
    // Fill 100% of the container / screen and track resizes and orientation
    // changes instead of running at a fixed 800x600.
    scale: {
        mode: Phaser.Scale.RESIZE,
        parent: 'phaser-example',
        width: '100%',
        height: '100%'
    },
    // Load images through an <img> tag instead of Phaser's default XHR/blob path.
    // Under file:// in the Cordova WebView, XHR for local files is unreliable, so
    // the default path could still fail before create() and leave a black screen.
    // <img> loading works with file:// URLs, keeping the flame sheets loadable in
    // the APK as well as on the web.
    loader: {
        imageLoadType: 'HTMLImageElement'
    }
};

const game = new Phaser.Game(config);
