class Example extends Phaser.Scene
{
    constructor ()
    {
        super();
    }

    preload ()
    {
        // Assets live in the /assets folder served at the site root (and copied
        // into the Cordova www/ root for the APK build). setBaseURL is kept
        // root-relative - with no directory climbing - so the same path resolves
        // whether the example runs from GitHub Pages or a file:// WebView.
        this.load.setBaseURL('assets');

        // An 8-frame animated flames sheet (128x160 per frame) plus a matching
        // normal-map sheet, generated by SpriteX. Passing an array of two URLs to
        // load.spritesheet registers the second image as the texture's normal-map
        // data source, so every frame carries its own surface normals and can be
        // lit per-pixel by the Light2D pipeline. Loading as a spritesheet (rather
        // than an atlas) avoids a JSON fetch, which keeps it working under the
        // file:// protocol inside the Cordova WebView.
        //   [0] bg-flames.png            colour (diffuse)
        //   [1] bg-flames-normalmap.png  surface normals (RGB = XYZ)
        this.load.spritesheet(
            'flames',
            [ 'bg-flames.png', 'bg-flames-normalmap.png' ],
            { frameWidth: 128, frameHeight: 160 }
        );
    }

    create ()
    {
        // Loop through the 8 sheet frames to animate the fire.
        this.anims.create({
            key: 'burn',
            frames: this.anims.generateFrameNumbers('flames', { start: 0, end: 7 }),
            frameRate: 12,
            repeat: -1
        });

        // Enable lighting and drop the ambient level so the moving lights read
        // clearly against the dark background.
        this.lights.enable();
        this.lights.setAmbientColor(0x1a1a1a);

        // Build a wall of flames across the bottom of the canvas. Each sprite is
        // routed through Light2D (setLighting), plays the shared animation from a
        // staggered frame for variety, and is lit entirely via its normal map.
        const frameWidth = 128;
        const scale = 1.9;
        const step = frameWidth * scale * 0.82;

        this.flames = [];

        for (let x = -step * 0.5; x < this.scale.width + step; x += step)
        {
            const flame = this.add.sprite(x, this.scale.height + 10, 'flames')
                .setOrigin(0.5, 1)
                .setScale(scale)
                .setLighting(true)
                .play('burn');

            // Desync each column so the wall shimmers rather than pulsing as one.
            flame.anims.setProgress(Math.abs(Math.sin(x)));

            this.flames.push(flame);
        }

        // A warm key light that follows the pointer - drag it across the flames
        // to watch the normal map catch the fire ridge by ridge.
        this.mouseLight = this.lights.addLight(400, 400, 360, 0xffb060, 3);

        // Two coloured lights sweeping the scene for constant motion.
        this.orbitA = this.lights.addLight(0, 0, 280, 0x3366ff, 2.2);
        this.orbitB = this.lights.addLight(0, 0, 280, 0xff2288, 2.2);

        this.input.on('pointermove', (pointer) =>
        {
            this.mouseLight.x = pointer.x;
            this.mouseLight.y = pointer.y;
        });

        // Click to cycle the key light through a small palette.
        const colors = [ 0xffb060, 0xffffff, 0x00ffcc, 0xff2222, 0x66ff33 ];
        let current = 0;

        this.input.on('pointerdown', () =>
        {
            current = (current + 1) % colors.length;
            this.mouseLight.setColor(colors[current]);
        });

        // Captions.
        this.add.text(16, 16, 'Normal Map Lighting', {
            fontFamily: 'Arial, sans-serif',
            fontSize: '28px',
            color: '#ffffff',
            stroke: '#000000',
            strokeThickness: 4
        });

        this.add.text(16, 52, 'move the pointer to light the flames • click to change colour', {
            fontFamily: 'Arial, sans-serif',
            fontSize: '16px',
            color: '#ffd9aa',
            stroke: '#000000',
            strokeThickness: 3
        });
    }

    update (time)
    {
        const cx = this.scale.width / 2;

        // Sweep the two coloured lights on opposite paths above the flames.
        this.orbitA.x = cx + Math.cos(time / 900) * 340;
        this.orbitA.y = 260 + Math.sin(time / 900) * 150;

        this.orbitB.x = cx + Math.cos(time / 1300 + Math.PI) * 320;
        this.orbitB.y = 300 + Math.sin(time / 1300 + Math.PI) * 150;
    }
}

const config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    backgroundColor: '#000000',
    scene: Example,
    pixelArt: true
};

const game = new Phaser.Game(config);
